In [6]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

El par(α, β) determina la orientación de la familia y s selecciona uno de sus rayos

In [15]:
#a)

def mascara_rayo(n, direccion, s):
    res =  np.zeros((n, n))
    for i in range(n) :
        for j in range(n):
            if (direccion[0]*i + direccion[1]*j) == s:
                res[i,j] =1
    return res


In [28]:
#b) Visualizar las máscaras para las direcciones (1, 0), (0, 1), (1, 1), (1, −1) y (2, 1), 
# utilizando respectivamente los desplazamientos s = 3, 5, 7, 0, 8.

m1=mascara_rayo(8, (1,0), 3)
m2=mascara_rayo(8, (0, 1), 5)
m3=mascara_rayo(8, (1, 1), 7)
m4=mascara_rayo(8, (1, -1), 0)
m5=mascara_rayo(8, (2, 1), 8)

print(m2)

[[0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]


In [26]:
#c)

X_fantoma = np.array([
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.8, 0.3, 0.3, 0.3, 0.0, 0.0],
[0.0, 0.8, 0.8, 0.8, 0.3, 0.3, 0.3, 0.0],
[0.0, 0.3, 0.8, 0.3, 0.3, 0.3, 0.3, 0.0],
[0.0, 0.3, 0.3, 0.3, 0.3, 0.5, 0.3, 0.0],
[0.0, 0.3, 0.3, 0.3, 0.5, 0.5, 0.5, 0.0],
[0.0, 0.0, 0.3, 0.3, 0.3, 0.5, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
], dtype=float)

b1 = (m1 * X_fantoma).sum()
b2 = (m2 * X_fantoma).sum()
b3 = (m3 * X_fantoma).sum()
b4 = (m4 * X_fantoma).sum()
b5 = (m5 * X_fantoma).sum()

print("b1 =", b1)
print("b2 =", b2)
print("b3 =", b3)
print("b4 =", b4)
print("b5 =", b5)

b1 = 2.3
b2 = 2.4
b3 = 1.2
b4 = 1.9000000000000001
b5 = 1.1


#d
Dos rayos con orientaciones diferentes pueden dar la misma medicion porque lo que mide es la suma de las atenuaciones de los pixeles seleccionados. Aunque selecciones pixeles distintos, esas sumas pueden dar el  mismo resultado.